package src.Lugares;

public enum Provincias {
    BUENOSAIRES, CIUDADAUTÓNOMADEBUENOSAIRES, CATAMARCA, CHACO, CHUBUT, CÓRDOBA, CORRIENTES, ENTRERÍOS, FORMOSA, JUJUY, LAPAMPA, LARIOJA, MENDOZA, MISIONES, NEUQUÉN, RÍONEGRO, SALTA, SANJUAN, SANLUIS, SANTACRUZ, SANTAFE, SANTIAGODELESTERO, TIERRADELFUEGOANTÁRTIDAEISLASDELATLÁNTICOSUR, TUCUMÁN


}
